name: tg
description: Telegram Client API (MTProto) to connect to Telegram and control a user programmatically.
version: 0.0.16
homepage: https://pwa.ir
repository: https://github.com/telegramflutter/tg
topics:
 - telegram
 - tdlib
 - mtproto
 
environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  t: ">=1.0.0 <222.0.0"
  archive: ^4.0.7
  pointycastle: ^4.0.0
  cryptography: ^2.7.0
  json_annotation: ^4.9.0
  socks5_proxy: ^2.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
